name: Kim Jin Woo
author: Herring Cove
baseurl: /herring-cove
description: theme for jekyll
github: http://www.github.com/tigre911
instagram: http://www.instagram.com
tistory: https://tigre911.tistory.com/
velog: https://velog.io/@tigre911
email: tmvhswlqkqn_@naver.com
location: Korea Daejeon
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
